Install numpy and torch using
%pip install numpy
%pip install torch

In [27]:
import numpy as np
import torch

#### Tensor creation using numpy

In [28]:
arr = np.arange(1, 5)

In [29]:
tensor_1 = torch.tensor(arr)

In [30]:
tensor_1

tensor([1, 2, 3, 4])

In [34]:
tensor_2 = torch.from_numpy(arr)

In [32]:
tensor_2

tensor([1., 2., 3., 4.])

#### torch.tensor(arr) Vs torch.from_numpy(arr)

In [36]:
arr[0] = 999

In [37]:
tensor_1

tensor([1, 2, 3, 4])

In [38]:
tensor_2

tensor([999,   2,   3,   4])

In [ ]:
#### tensor creation without numPy

In [39]:
torch.empty(2)

tensor([6.6310e-07, 1.0314e-08])

In [44]:
tensor_onces = torch.ones(2,2)

In [45]:
tensor_onces.dtype

torch.float32